// Generated by gencpp from file end_effector_control/JointRateCommand.msg
// DO NOT EDIT!


#ifndef END_EFFECTOR_CONTROL_MESSAGE_JOINTRATECOMMAND_H
#define END_EFFECTOR_CONTROL_MESSAGE_JOINTRATECOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace end_effector_control
{
template <class ContainerAllocator>
struct JointRateCommand_
{
  typedef JointRateCommand_<ContainerAllocator> Type;

  JointRateCommand_()
    : axis(0)
    , desiredRate(0.0)  {
    }
  JointRateCommand_(const ContainerAllocator& _alloc)
    : axis(0)
    , desiredRate(0.0)  {
  (void)_alloc;
    }



   typedef int8_t _axis_type;
  _axis_type axis;

   typedef double _desiredRate_type;
  _desiredRate_type desiredRate;





  typedef boost::shared_ptr< ::end_effector_control::JointRateCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::end_effector_control::JointRateCommand_<ContainerAllocator> const> ConstPtr;

}; // struct JointRateCommand_

typedef ::end_effector_control::JointRateCommand_<std::allocator<void> > JointRateCommand;

typedef boost::shared_ptr< ::end_effector_control::JointRateCommand > JointRateCommandPtr;
typedef boost::shared_ptr< ::end_effector_control::JointRateCommand const> JointRateCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::end_effector_control::JointRateCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::end_effector_control::JointRateCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace end_effector_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['C:/Program Files/MATLAB/R2021b/sys/ros1/win64/ros1/share/std_msgs/cmake/../msg'], 'end_effector_control': ['C:/Users/trbin/Documents/GitHub/ASTRA_Arm_Inverse_Kinematics_Pre-Calculator/ArmIK/packages/matlab_msg_gen_ros1/win64/src/end_effector_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::end_effector_control::JointRateCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::end_effector_control::JointRateCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::end_effector_control::JointRateCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::end_effector_control::JointRateCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::end_effector_control::JointRateCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::end_effector_control::JointRateCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::end_effector_control::JointRateCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c9621cdf3b2746e88f21114aece282c";
  }

  static const char* value(const ::end_effector_control::JointRateCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c9621cdf3b2746eULL;
  static const uint64_t static_value2 = 0x88f21114aece282cULL;
};

template<class ContainerAllocator>
struct DataType< ::end_effector_control::JointRateCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "end_effector_control/JointRateCommand";
  }

  static const char* value(const ::end_effector_control::JointRateCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::end_effector_control::JointRateCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int8 axis\n"
"float64 desiredRate\n"
;
  }

  static const char* value(const ::end_effector_control::JointRateCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::end_effector_control::JointRateCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axis);
      stream.next(m.desiredRate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointRateCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::end_effector_control::JointRateCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::end_effector_control::JointRateCommand_<ContainerAllocator>& v)
  {
    s << indent << "axis: ";
    Printer<int8_t>::stream(s, indent + "  ", v.axis);
    s << indent << "desiredRate: ";
    Printer<double>::stream(s, indent + "  ", v.desiredRate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // END_EFFECTOR_CONTROL_MESSAGE_JOINTRATECOMMAND_H
