
classdef HomeArmBaseRequest < ros.Message
    %HomeArmBaseRequest MATLAB implementation of arm_relay/HomeArmBaseRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'arm_relay/HomeArmBaseRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1469f3de6d455ddf134567e609eae6e6' % The MD5 Checksum of the message definition
        PropertyList = {} % List of non-constant message properties
        ROSPropertyList = {} % List of non-constant ROS message properties
        PropertyMessageTypes = {} % Types of contained nested messages
    end
    properties (Constant)
        Home = logical(1);
    end
    properties
    end
    methods
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.arm_relay.HomeArmBaseRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.arm_relay.HomeArmBaseRequest(strObj);
        end
    end
end
