// Generated by gencpp from file arm_relay/HomeArmBase.msg
// DO NOT EDIT!


#ifndef ARM_RELAY_MESSAGE_HOMEARMBASE_H
#define ARM_RELAY_MESSAGE_HOMEARMBASE_H

#include <ros/service_traits.h>


#include <arm_relay/HomeArmBaseRequest.h>
#include <arm_relay/HomeArmBaseResponse.h>


namespace arm_relay
{

struct HomeArmBase
{

typedef HomeArmBaseRequest Request;
typedef HomeArmBaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HomeArmBase
} // namespace arm_relay


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_relay::HomeArmBase > {
  static const char* value()
  {
    return "2489954a46d40c91afe244fac3b4fac9";
  }

  static const char* value(const ::arm_relay::HomeArmBase&) { return value(); }
};

template<>
struct DataType< ::arm_relay::HomeArmBase > {
  static const char* value()
  {
    return "arm_relay/HomeArmBase";
  }

  static const char* value(const ::arm_relay::HomeArmBase&) { return value(); }
};


// service_traits::MD5Sum< ::arm_relay::HomeArmBaseRequest> should match 
// service_traits::MD5Sum< ::arm_relay::HomeArmBase > 
template<>
struct MD5Sum< ::arm_relay::HomeArmBaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_relay::HomeArmBase >::value();
  }
  static const char* value(const ::arm_relay::HomeArmBaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_relay::HomeArmBaseRequest> should match 
// service_traits::DataType< ::arm_relay::HomeArmBase > 
template<>
struct DataType< ::arm_relay::HomeArmBaseRequest>
{
  static const char* value()
  {
    return DataType< ::arm_relay::HomeArmBase >::value();
  }
  static const char* value(const ::arm_relay::HomeArmBaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_relay::HomeArmBaseResponse> should match 
// service_traits::MD5Sum< ::arm_relay::HomeArmBase > 
template<>
struct MD5Sum< ::arm_relay::HomeArmBaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_relay::HomeArmBase >::value();
  }
  static const char* value(const ::arm_relay::HomeArmBaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_relay::HomeArmBaseResponse> should match 
// service_traits::DataType< ::arm_relay::HomeArmBase > 
template<>
struct DataType< ::arm_relay::HomeArmBaseResponse>
{
  static const char* value()
  {
    return DataType< ::arm_relay::HomeArmBase >::value();
  }
  static const char* value(const ::arm_relay::HomeArmBaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_RELAY_MESSAGE_HOMEARMBASE_H
