// Generated by gencpp from file endeffector_controller/EnableServos.msg
// DO NOT EDIT!


#ifndef ENDEFFECTOR_CONTROLLER_MESSAGE_ENABLESERVOS_H
#define ENDEFFECTOR_CONTROLLER_MESSAGE_ENABLESERVOS_H

#include <ros/service_traits.h>


#include <endeffector_controller/EnableServosRequest.h>
#include <endeffector_controller/EnableServosResponse.h>


namespace endeffector_controller
{

struct EnableServos
{

typedef EnableServosRequest Request;
typedef EnableServosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableServos
} // namespace endeffector_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::endeffector_controller::EnableServos > {
  static const char* value()
  {
    return "da9e2563ede369d1290fb3803a11ebb5";
  }

  static const char* value(const ::endeffector_controller::EnableServos&) { return value(); }
};

template<>
struct DataType< ::endeffector_controller::EnableServos > {
  static const char* value()
  {
    return "endeffector_controller/EnableServos";
  }

  static const char* value(const ::endeffector_controller::EnableServos&) { return value(); }
};


// service_traits::MD5Sum< ::endeffector_controller::EnableServosRequest> should match 
// service_traits::MD5Sum< ::endeffector_controller::EnableServos > 
template<>
struct MD5Sum< ::endeffector_controller::EnableServosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::endeffector_controller::EnableServos >::value();
  }
  static const char* value(const ::endeffector_controller::EnableServosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::endeffector_controller::EnableServosRequest> should match 
// service_traits::DataType< ::endeffector_controller::EnableServos > 
template<>
struct DataType< ::endeffector_controller::EnableServosRequest>
{
  static const char* value()
  {
    return DataType< ::endeffector_controller::EnableServos >::value();
  }
  static const char* value(const ::endeffector_controller::EnableServosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::endeffector_controller::EnableServosResponse> should match 
// service_traits::MD5Sum< ::endeffector_controller::EnableServos > 
template<>
struct MD5Sum< ::endeffector_controller::EnableServosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::endeffector_controller::EnableServos >::value();
  }
  static const char* value(const ::endeffector_controller::EnableServosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::endeffector_controller::EnableServosResponse> should match 
// service_traits::DataType< ::endeffector_controller::EnableServos > 
template<>
struct DataType< ::endeffector_controller::EnableServosResponse>
{
  static const char* value()
  {
    return DataType< ::endeffector_controller::EnableServos >::value();
  }
  static const char* value(const ::endeffector_controller::EnableServosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ENDEFFECTOR_CONTROLLER_MESSAGE_ENABLESERVOS_H
