// Generated by gencpp from file endeffector_controller/Home.msg
// DO NOT EDIT!


#ifndef ENDEFFECTOR_CONTROLLER_MESSAGE_HOME_H
#define ENDEFFECTOR_CONTROLLER_MESSAGE_HOME_H

#include <ros/service_traits.h>


#include <endeffector_controller/HomeRequest.h>
#include <endeffector_controller/HomeResponse.h>


namespace endeffector_controller
{

struct Home
{

typedef HomeRequest Request;
typedef HomeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Home
} // namespace endeffector_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::endeffector_controller::Home > {
  static const char* value()
  {
    return "2489954a46d40c91afe244fac3b4fac9";
  }

  static const char* value(const ::endeffector_controller::Home&) { return value(); }
};

template<>
struct DataType< ::endeffector_controller::Home > {
  static const char* value()
  {
    return "endeffector_controller/Home";
  }

  static const char* value(const ::endeffector_controller::Home&) { return value(); }
};


// service_traits::MD5Sum< ::endeffector_controller::HomeRequest> should match 
// service_traits::MD5Sum< ::endeffector_controller::Home > 
template<>
struct MD5Sum< ::endeffector_controller::HomeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::endeffector_controller::Home >::value();
  }
  static const char* value(const ::endeffector_controller::HomeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::endeffector_controller::HomeRequest> should match 
// service_traits::DataType< ::endeffector_controller::Home > 
template<>
struct DataType< ::endeffector_controller::HomeRequest>
{
  static const char* value()
  {
    return DataType< ::endeffector_controller::Home >::value();
  }
  static const char* value(const ::endeffector_controller::HomeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::endeffector_controller::HomeResponse> should match 
// service_traits::MD5Sum< ::endeffector_controller::Home > 
template<>
struct MD5Sum< ::endeffector_controller::HomeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::endeffector_controller::Home >::value();
  }
  static const char* value(const ::endeffector_controller::HomeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::endeffector_controller::HomeResponse> should match 
// service_traits::DataType< ::endeffector_controller::Home > 
template<>
struct DataType< ::endeffector_controller::HomeResponse>
{
  static const char* value()
  {
    return DataType< ::endeffector_controller::Home >::value();
  }
  static const char* value(const ::endeffector_controller::HomeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ENDEFFECTOR_CONTROLLER_MESSAGE_HOME_H
