// Generated by gencpp from file arm_relay/EnableActuators.msg
// DO NOT EDIT!


#ifndef ARM_RELAY_MESSAGE_ENABLEACTUATORS_H
#define ARM_RELAY_MESSAGE_ENABLEACTUATORS_H

#include <ros/service_traits.h>


#include <arm_relay/EnableActuatorsRequest.h>
#include <arm_relay/EnableActuatorsResponse.h>


namespace arm_relay
{

struct EnableActuators
{

typedef EnableActuatorsRequest Request;
typedef EnableActuatorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableActuators
} // namespace arm_relay


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arm_relay::EnableActuators > {
  static const char* value()
  {
    return "da9e2563ede369d1290fb3803a11ebb5";
  }

  static const char* value(const ::arm_relay::EnableActuators&) { return value(); }
};

template<>
struct DataType< ::arm_relay::EnableActuators > {
  static const char* value()
  {
    return "arm_relay/EnableActuators";
  }

  static const char* value(const ::arm_relay::EnableActuators&) { return value(); }
};


// service_traits::MD5Sum< ::arm_relay::EnableActuatorsRequest> should match 
// service_traits::MD5Sum< ::arm_relay::EnableActuators > 
template<>
struct MD5Sum< ::arm_relay::EnableActuatorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arm_relay::EnableActuators >::value();
  }
  static const char* value(const ::arm_relay::EnableActuatorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_relay::EnableActuatorsRequest> should match 
// service_traits::DataType< ::arm_relay::EnableActuators > 
template<>
struct DataType< ::arm_relay::EnableActuatorsRequest>
{
  static const char* value()
  {
    return DataType< ::arm_relay::EnableActuators >::value();
  }
  static const char* value(const ::arm_relay::EnableActuatorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arm_relay::EnableActuatorsResponse> should match 
// service_traits::MD5Sum< ::arm_relay::EnableActuators > 
template<>
struct MD5Sum< ::arm_relay::EnableActuatorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arm_relay::EnableActuators >::value();
  }
  static const char* value(const ::arm_relay::EnableActuatorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arm_relay::EnableActuatorsResponse> should match 
// service_traits::DataType< ::arm_relay::EnableActuators > 
template<>
struct DataType< ::arm_relay::EnableActuatorsResponse>
{
  static const char* value()
  {
    return DataType< ::arm_relay::EnableActuators >::value();
  }
  static const char* value(const ::arm_relay::EnableActuatorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARM_RELAY_MESSAGE_ENABLEACTUATORS_H
