function T_1_to_0 = T_1_to_0_f(in1)
%T_1_to_0_f
%    T_1_to_0 = T_1_to_0_f(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Feb-2022 00:12:27

theta1 = in1(:,1);
t2 = cos(theta1);
t3 = sin(theta1);
T_1_to_0 = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.4092e-1,1.0],[4,4]);
