function T_2_to_1 = T_2_to_1_f(in1)
%T_2_to_1_f
%    T_2_to_1 = T_2_to_1_f(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Feb-2022 00:12:27

theta2 = in1(:,2);
t2 = cos(theta2);
t3 = sin(theta2);
T_2_to_1 = reshape([t2,0.0,t3,0.0,-t3,0.0,t2,0.0,0.0,-1.0,0.0,0.0,3.48e-3,0.0,0.0,1.0],[4,4]);
