function T_3_to_2 = T_3_to_2_f(in1)
%T_3_to_2_f
%    T_3_to_2 = T_3_to_2_f(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Feb-2022 00:12:27

theta3 = in1(:,3);
t2 = cos(theta3);
t3 = sin(theta3);
T_3_to_2 = reshape([t2,t3,0.0,0.0,-t3,t2,0.0,0.0,0.0,0.0,1.0,0.0,1.4e+1./2.5e+1,0.0,0.0,1.0],[4,4]);
