function T_5_to_4 = T_5_to_4_f(in1)
%T_5_to_4_f
%    T_5_to_4 = T_5_to_4_f(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Feb-2022 00:12:28

theta5 = in1(:,5);
t2 = pi./2.0;
t3 = t2+theta5;
t4 = cos(t3);
t5 = sin(t3);
t6 = -t5;
T_5_to_4 = reshape([t4,0.0,t6,0.0,t6,0.0,-t4,0.0,0.0,1.0,0.0,0.0,7.171e-2,2.517e-2,0.0,1.0],[4,4]);
