function T_6_to_5 = T_6_to_5_f(in1)
%T_6_to_5_f
%    T_6_to_5 = T_6_to_5_f(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Feb-2022 00:12:28

theta6 = in1(:,6);
t2 = cos(theta6);
t3 = sin(theta6);
T_6_to_5 = reshape([t2,0.0,t3,0.0,-t3,0.0,t2,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
