function out1 = T_H_to_6_f(in1)
%T_H_to_6_f
%    OUT1 = T_H_to_6_f(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    26-Feb-2022 00:12:28

out1 = reshape([0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.1744e-1,1.0],[4,4]);
