// Generated by gencpp from file end_effector_control/EnableServos.msg
// DO NOT EDIT!


#ifndef END_EFFECTOR_CONTROL_MESSAGE_ENABLESERVOS_H
#define END_EFFECTOR_CONTROL_MESSAGE_ENABLESERVOS_H

#include <ros/service_traits.h>


#include <end_effector_control/EnableServosRequest.h>
#include <end_effector_control/EnableServosResponse.h>


namespace end_effector_control
{

struct EnableServos
{

typedef EnableServosRequest Request;
typedef EnableServosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableServos
} // namespace end_effector_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::end_effector_control::EnableServos > {
  static const char* value()
  {
    return "da9e2563ede369d1290fb3803a11ebb5";
  }

  static const char* value(const ::end_effector_control::EnableServos&) { return value(); }
};

template<>
struct DataType< ::end_effector_control::EnableServos > {
  static const char* value()
  {
    return "end_effector_control/EnableServos";
  }

  static const char* value(const ::end_effector_control::EnableServos&) { return value(); }
};


// service_traits::MD5Sum< ::end_effector_control::EnableServosRequest> should match 
// service_traits::MD5Sum< ::end_effector_control::EnableServos > 
template<>
struct MD5Sum< ::end_effector_control::EnableServosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::end_effector_control::EnableServos >::value();
  }
  static const char* value(const ::end_effector_control::EnableServosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::end_effector_control::EnableServosRequest> should match 
// service_traits::DataType< ::end_effector_control::EnableServos > 
template<>
struct DataType< ::end_effector_control::EnableServosRequest>
{
  static const char* value()
  {
    return DataType< ::end_effector_control::EnableServos >::value();
  }
  static const char* value(const ::end_effector_control::EnableServosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::end_effector_control::EnableServosResponse> should match 
// service_traits::MD5Sum< ::end_effector_control::EnableServos > 
template<>
struct MD5Sum< ::end_effector_control::EnableServosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::end_effector_control::EnableServos >::value();
  }
  static const char* value(const ::end_effector_control::EnableServosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::end_effector_control::EnableServosResponse> should match 
// service_traits::DataType< ::end_effector_control::EnableServos > 
template<>
struct DataType< ::end_effector_control::EnableServosResponse>
{
  static const char* value()
  {
    return DataType< ::end_effector_control::EnableServos >::value();
  }
  static const char* value(const ::end_effector_control::EnableServosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // END_EFFECTOR_CONTROL_MESSAGE_ENABLESERVOS_H
