// Generated by gencpp from file end_effector_control/HomeRequest.msg
// DO NOT EDIT!


#ifndef END_EFFECTOR_CONTROL_MESSAGE_HOMEREQUEST_H
#define END_EFFECTOR_CONTROL_MESSAGE_HOMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace end_effector_control
{
template <class ContainerAllocator>
struct HomeRequest_
{
  typedef HomeRequest_<ContainerAllocator> Type;

  HomeRequest_()
    {
    }
  HomeRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  static const uint8_t home;

  typedef boost::shared_ptr< ::end_effector_control::HomeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::end_effector_control::HomeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HomeRequest_

typedef ::end_effector_control::HomeRequest_<std::allocator<void> > HomeRequest;

typedef boost::shared_ptr< ::end_effector_control::HomeRequest > HomeRequestPtr;
typedef boost::shared_ptr< ::end_effector_control::HomeRequest const> HomeRequestConstPtr;

// constants requiring out of line definition

   
   template<typename ContainerAllocator> const uint8_t
      HomeRequest_<ContainerAllocator>::home =
        
           1
        
        ;
   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::end_effector_control::HomeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::end_effector_control::HomeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace end_effector_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['C:/Program Files/MATLAB/R2021b/sys/ros1/win64/ros1/share/std_msgs/cmake/../msg'], 'end_effector_control': ['C:/Users/trbin/Documents/GitHub/ASTRA_Arm_Inverse_Kinematics_Pre-Calculator/ArmIK/packages/matlab_msg_gen_ros1/win64/src/end_effector_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::end_effector_control::HomeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::end_effector_control::HomeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::end_effector_control::HomeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::end_effector_control::HomeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::end_effector_control::HomeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::end_effector_control::HomeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::end_effector_control::HomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1469f3de6d455ddf134567e609eae6e6";
  }

  static const char* value(const ::end_effector_control::HomeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1469f3de6d455ddfULL;
  static const uint64_t static_value2 = 0x134567e609eae6e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::end_effector_control::HomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "end_effector_control/HomeRequest";
  }

  static const char* value(const ::end_effector_control::HomeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::end_effector_control::HomeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"bool home=1\n"
;
  }

  static const char* value(const ::end_effector_control::HomeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::end_effector_control::HomeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HomeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::end_effector_control::HomeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::end_effector_control::HomeRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // END_EFFECTOR_CONTROL_MESSAGE_HOMEREQUEST_H
