
classdef ActuatorFeedback < ros.Message
    %ActuatorFeedback MATLAB implementation of endeffector_controller/ActuatorFeedback
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'endeffector_controller/ActuatorFeedback' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '4e86de48d5d451a19d9f7d58a318f00f' % The MD5 Checksum of the message definition
        PropertyList = { 'Axis' 'Angle' 'ActualRate' } % List of non-constant message properties
        ROSPropertyList = { 'axis' 'angle' 'actualRate' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Axis
        Angle
        ActualRate
    end
    methods
        function set.Axis(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ActuatorFeedback', 'Axis');
            obj.Axis = int8(val);
        end
        function set.Angle(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ActuatorFeedback', 'Angle');
            obj.Angle = double(val);
        end
        function set.ActualRate(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ActuatorFeedback', 'ActualRate');
            obj.ActualRate = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.endeffector_controller.ActuatorFeedback.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.endeffector_controller.ActuatorFeedback(strObj);
        end
    end
end
