
classdef EnableServosResponse < ros.Message
    %EnableServosResponse MATLAB implementation of endeffector_controller/EnableServosResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'endeffector_controller/EnableServosResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2815464f55ab63684cc1bc38072d0b9b' % The MD5 Checksum of the message definition
        PropertyList = { 'Enabled' } % List of non-constant message properties
        ROSPropertyList = { 'enabled' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Enabled
    end
    methods
        function set.Enabled(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'EnableServosResponse', 'Enabled');
            obj.Enabled = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.endeffector_controller.EnableServosResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.endeffector_controller.EnableServosResponse(strObj);
        end
    end
end
